generator:
  class: sfDoctrineGenerator
  param:
    model_class:           worksheet
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          worksheet
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [id]
      filter:
        class: false
      form:    ~
      edit:    ~
      new:     ~
