<?php

/**
 * DistributorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DistributorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DistributorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Distributor');
    }
}