<?php

/**
 * History
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    aloha
 * @subpackage model
 * @author     Alexander Manichev a.manichev@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class History extends BaseHistory
{
	public static $eventCode = array(
		10 => 'Создание',
		20 => 'Редактирование',
		30 => 'Удаление',

		40 => 'Загружено фото',
		50 => 'Загружено аудио',

		60 => 'Удалено фото',
		70 => 'Удалено аудио',

		80 => 'Одобрено',
		90 => 'Одобрено фото',
		100 => 'Одобрено аудио',

		110 => 'Возвращено',
		120 => 'Возвращено фото',
		130 => 'Возвращено аудио',

		140 => 'Изменен аудитор'
	);

	public static $modelRus = array(
		'Worksheet' => 'Анкета'
	);

	public static $modelRusLink = array(
		'Worksheet' => array(
			'route' => array(
				10 => 'auditor_panel_add_worksheet',
				20 => 'auditor_panel_add_worksheet',
				30 => 'auditor_panel_add_worksheet',

				40 => 'auditor_panel_worksheet_additional_files',
				50 => 'auditor_panel_worksheet_additional_files',

				60 => 'auditor_panel_worksheet_additional_files',
				70 => 'auditor_panel_worksheet_additional_files',

				80 => 'auditor_panel_add_worksheet',
				90 => 'auditor_panel_worksheet_additional_files',
				100 => 'auditor_panel_worksheet_additional_files',

				110 => 'auditor_panel_add_worksheet',
				120 => 'auditor_panel_worksheet_additional_files',
				130 => 'auditor_panel_worksheet_additional_files',

				140 => 'auditor_panel_add_worksheet'),

			'object' => 'getOutlet'),
	);

	public static function log($event, $object, $user, $comment = false)
	{
		$history = new History();
		$history->setEvent($event);
		$history->setModel(get_class($object));
		$history->setModelId($object->getId());

		if($user instanceof myUser)
			$user = $user->getGuardUser();

		$history->setSfGuardUser($user);

		if($comment)
			$history->setComment($comment);

		$history->save();
	}
}
