<?php

/**
 * OutletTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OutletTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OutletTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Outlet');
    }
}