<?php

/**
 * RegionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RegionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Region');
    }

	public function getAllOrderedQuery()
	{
		$q = $this->createQuery('region');
		$q->orderBy('name ASC');

		return $q;
	}
}