project_manager:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               project_manager
    prefix_path:          /project_manager
    column:               id
    with_wildcard_routes: true

auditors:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               auditor
    prefix_path:          /auditor
    column:               id
    with_wildcard_routes: true

coordinator:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               coordinator
    prefix_path:          /coordinator
    column:               id
    with_wildcard_routes: true

worksheet:
  class: sfDoctrineRouteCollection
  options:
    model:                worksheet
    module:               worksheet
    prefix_path:          /worksheet
    column:               id
    with_wildcard_routes: true

user:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               user
    prefix_path:          /user
    column:               id
    with_wildcard_routes: true
    collection_actions:
      newAuditor:           [get,post]
      newCoordinator:       [get,post]

outlet:
  class: sfDoctrineRouteCollection
  options:
    model:                outlet
    module:               outlet
    prefix_path:          /outlet
    column:               id
    with_wildcard_routes: true
    collection_actions:
      parseFile:           [get,post]
      parseFile_create:    [post]

city:
  class: sfDoctrineRouteCollection
  options:
    model:                city
    module:               city
    prefix_path:          /city
    column:               id
    with_wildcard_routes: true

region:
  class: sfDoctrineRouteCollection
  options:
    model:                region
    module:               region
    prefix_path:          /region
    column:               id
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: index, action: index }

signout:
  url: /signout
  param: {module: sfGuardAuth, action: signout}

signin_by_tocken:
  class: sfDoctrineRoute
  url: /signin/tocken/:tocken
  param: {module: sfGuardAuth, action: signinByTocken}
  options:
    model: sfGuardUser
    type: object
#  requirements:
#    sf_method: [get]
#    tocken: \w+

auditor:
  url: /auditor
  param: {module: auditor_panel, action: auditor }

auditor_panel:
  url: /auditor/panel
  param: {module: auditor_panel, action: index }

auditor_panel_add_worksheet:
  class: sfDoctrineRoute
  url: /auditor/panel/outlet/:id/worksheet
  param: {module: auditor_panel, action: addWorksheet }
  options:
    model: outlet
    type: object
  requirements:
    sf_method: [get, post]

auditor_panel_approve_worksheet:
  class: sfDoctrineRoute
  url: /auditor/panel/outlet/:id/worksheet/approve
  param: {module: auditor_panel, action: approveWorksheet }
  options:
    model: outlet
    type: object
  requirements:
    sf_method: [get]

auditor_panel_disapprove_worksheet:
  class: sfDoctrineRoute
  url: /auditor/panel/outlet/:id/worksheet/disapprove
  param: {module: auditor_panel, action: disapproveWorksheet }
  options:
    model: outlet
    type: object
  requirements:
    sf_method: [get]

auditor_panel_approve_worksheet_photo:
  class: sfDoctrineRoute
  url: /auditor/panel/outlet/:id/worksheet/approve/photo
  param: {module: auditor_panel, action: approveWorksheetPhoto }
  options:
    model: outlet
    type: object
  requirements:
    sf_method: [get]

auditor_panel_disapprove_worksheet_photo:
  class: sfDoctrineRoute
  url: /auditor/panel/outlet/:id/worksheet/disapprove/photo
  param: {module: auditor_panel, action: disapproveWorksheetPhoto }
  options:
    model: outlet
    type: object
  requirements:
    sf_method: [get]

auditor_panel_approve_worksheet_audio:
  class: sfDoctrineRoute
  url: /auditor/panel/outlet/:id/worksheet/approve/audio
  param: {module: auditor_panel, action: approveWorksheetAudio }
  options:
    model: outlet
    type: object
  requirements:
    sf_method: [get]

auditor_panel_disapprove_worksheet_audio:
  class: sfDoctrineRoute
  url: /auditor/panel/outlet/:id/worksheet/disapprove/audio
  param: {module: auditor_panel, action: disapproveWorksheetAudio }
  options:
    model: outlet
    type: object
  requirements:
    sf_method: [get]

auditor_panel_worksheet_additional_files:
  class: sfDoctrineRoute
  url: /auditor/panel/outlet/:id/worksheet/files
  param: {module: auditor_panel, action: additionalFiles }
  options:
    model: outlet
    type: object

auditor_panel_worksheet_additional_files_rename:
  class: sfDoctrineRoute
  url: /auditor/panel/outlet/:id/worksheet/files/rename
  param: {module: auditor_panel, action: additionalFilesRename }
  options:
    model: outlet
    type: object
  requirements:
    sf_method: [post]

auditor_panel_worksheet:
  class: sfDoctrineRouteCollection
  options:
    model:                worksheet
    module:               auditor_panel
    prefix_path:          /auditor/panel/worksheet
    column:               id
    with_wildcard_routes: true

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }
#
#default:
#  url:   /:module/:action/*
