<?php

/**
 * sfGuardUserRegionSchemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserRegionSchemaTable extends PluginsfGuardUserRegionSchemaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserRegionSchemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserRegionSchema');
    }
}