<?php

/**
 * sfGuardUserCitySchemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserCitySchemaTable extends PluginsfGuardUserCitySchemaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserCitySchemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserCitySchema');
    }
}