<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }

	public function getActiveCoordinators()
	{
		$coordinatorGroup = sfGuardGroupTable::getInstance()->findOneByName('coordinator', Doctrine::HYDRATE_ARRAY);
		$q = $this->createQuery('user');
		$q->addWhere('user.is_active = ?', true)
		->leftJoin('user.sfGuardUserGroup userGroup')
		->addWhere('userGroup.group_id = ?', $coordinatorGroup['id']);

		return $q;
	}
}