<?php

/**
 * Attachment
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    aloha
 * @subpackage model
 * @author     Alexander Manichev a.manichev@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Attachment extends PluginAttachment
{

	public function getBaseUploadPath()
	{
		$worksheet = Doctrine::getTable($this->getObjectClass())->findOneById($this->getObjectId());

		$outlet = $worksheet->getOutlet();

		$basePath = sfConfig::get('sf_upload_dir') . DS .
				strtolower($this->getObjectClass()) . DS .
				SlugifyClass::slugify($outlet->getRegion()) . DS .
				SlugifyClass::slugify($outlet->getCity()) . DS .
				SlugifyClass::slugify($outlet->getAddress()) . DS;

		return $basePath;
	}

}
