<?php

/**
 * AudioAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AudioAttachmentTable extends PluginAudioAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object AudioAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AudioAttachment');
    }
}