<?php

/**
 * CustomAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CustomAttachmentTable extends PluginCustomAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CustomAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CustomAttachment');
    }
}