<?php

/**
 * DocumentAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DocumentAttachmentTable extends PluginDocumentAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object DocumentAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DocumentAttachment');
    }
}