<?php

/**
 * ImageAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ImageAttachmentTable extends PluginImageAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ImageAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ImageAttachment');
    }
}