<?php

/**
 * LinkAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkAttachmentTable extends PluginLinkAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkAttachment');
    }
}