<?php

/**
 * ModelAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModelAttachmentTable extends PluginModelAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModelAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModelAttachment');
    }
}