<?php

/**
 * VideoAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VideoAttachmentTable extends PluginVideoAttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object VideoAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('VideoAttachment');
    }
}