generator:
  class: sfDoctrineGenerator
  param:
    model_class:           outlet
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          outlet
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        distributor: {label: Дистрибьютор }
        distributor_id: {label: Дистрибьютор }
        lagal_name: {label: Юридическое название }
        actual_name: {label: Фактическое название }
        region_id: {label: Регион }
        city_id: {label: Город }
        address: {label: Адрес }
        type: {label: Тип РТТ }
        group_type: {label: Группа }
      list:
        title: Список РТТ
        actions:
          parseFile: {label: Загрузить группу РТТ из файла }
          _new: ~
        display: [_distributor, lagal_name, actual_name, _region_id, _city_id, _type, group_type]
        table_method: getForList
      filter:  ~
      form:    ~
      edit:
        title: Редактирование РТТ
      new:
        title: Создание РТТ
