<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addWorkSheetTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('worksheet', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '11',
             ),
             'outlet_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'unsigned' => '1',
              'length' => '11',
             ),
             'cordiant_comfort_155_65r13_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_155_65r13_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_175_70r13_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_175_70r13_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_175_65r14_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_175_65r14_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_185_60r14_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_185_60r14_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_185_65r14_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_185_65r14_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_185_70r14_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_185_70r14_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_185_65r15_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_185_65r15_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_195_65r15_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_195_65r15_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_205_60r15_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_205_60r15_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_205_65r15_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_205_65r15_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_205_55r16_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_205_55r16_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_205_60r16_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_205_60r16_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_215_55r16_a' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'cordiant_comfort_215_55r16_b' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('worksheet');
    }
}