<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addWorksheetAuditStatusIndex extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('worksheet', 'audit_status_idx', array(
             'fields' => 
             array(
              0 => 'audit_status',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('worksheet', 'audit_status_idx', array(
             'fields' => 
             array(
              0 => 'audit_status',
             ),
             ));
    }
}