<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserEmailAddressNotUnique extends Doctrine_Migration_Base
{
	public function up()
	{
		$this->changeColumn('sf_guard_user', 'email_address', 'string', '255', array(
			'notnull' => '1',
		));
	}

	public function down()
	{
		$this->changeColumn('sf_guard_user', 'email_address', 'string', '255', array(
			'unique' => true, 'notnull' => '1'));
	}
}