<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class dropCountryFks extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('city', 'city_country_id_country_id');
        $this->dropForeignKey('region', 'region_country_id_country_id');
    }

    public function down()
    {
        $this->createForeignKey('city', 'city_country_id_country_id', array(
             'name' => 'city_country_id_country_id',
             'local' => 'country_id',
             'foreign' => 'id',
             'foreignTable' => 'country',
             ));
        $this->createForeignKey('region', 'region_country_id_country_id', array(
             'name' => 'region_country_id_country_id',
             'local' => 'country_id',
             'foreign' => 'id',
             'foreignTable' => 'country',
             ));
    }
}