<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class changeUserRegionSchema extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('sf_guard_user_region_schema', 'region_id', 'integer', '8', array(
             'primary' => '1',
             'unsigned' => '1',
             ));
    }

    public function down()
    {

    }
}