<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserAddTockenIndex extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('sf_guard_user', 'tockecn_idx', array(
             'fields' => 
             array(
              0 => 'tocken',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('sf_guard_user', 'tockecn_idx', array(
             'fields' => 
             array(
              0 => 'tocken',
             ),
             ));
    }
}