<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class updateWorkSheetTable extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('worksheet', 'cordiant_sport_175_70r13_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_175_70r13_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_175_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_175_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_175_70r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_175_70r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_185_60r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_185_60r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_185_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_185_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_185_70r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_185_70r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_185_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_185_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_195_60r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_195_60r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_195_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_195_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_205_60r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_205_60r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_205_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_205_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_205_55r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_205_55r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_215_55r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_215_55r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_175_70r13_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_175_70r13_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_175_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_175_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_175_70r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_175_70r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_185_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_185_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_185_70r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_185_70r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_185_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_185_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_195_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_standart_195_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_all_terrain_225_70r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_all_terrain_225_70r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_all_terrain_215_65r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_all_terrain_215_65r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_all_terrain_215_70r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_all_terrain_215_70r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_all_terrain_205_70r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_all_terrain_205_70r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_175_70r13_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_175_70r13_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_175_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_175_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_185_60r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_185_60r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_185_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_185_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_185_60r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_185_60r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_195_55r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_195_55r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_195_60r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_195_60r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_195_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_195_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_205_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_205_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_205_55r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_205_55r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_205_60r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_205_60r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_215_55r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_215_55r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_215_60r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_sport_2_215_60r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_155_70r13_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_155_70r13_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_185_70r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_185_70r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_205_60r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_205_60r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_185_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_185_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_195_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_195_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_205_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_205_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_205_55r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_205_55r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_185_60r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_185_60r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_175_70r13_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_175_70r13_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_175_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_road_runner_175_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_4_x_4_235_70r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_4_x_4_235_70r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_205_70r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_205_70r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_235_75r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_235_75r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_215_65r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_215_65r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_225_75r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_225_75r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_245_70r16_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'cordiant_off_road_245_70r16_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_ps_3_175_70r13_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_ps_3_175_70r13_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_175_70r13_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_175_70r13_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_175_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_175_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_185_60r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_185_60r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_185_65r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_185_65r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_185_70r14_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_185_70r14_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_195_65r15_a', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'tunga_camina_195_65r15_b', 'boolean', '25', array(
             ));
        $this->addColumn('worksheet', 'comment', 'text', '1024', array(
             ));
        $this->addColumn('worksheet', 'outlet_manager', 'string', '255', array(
             ));
        $this->addColumn('worksheet', 'outlet_manager_position', 'string', '255', array(
             ));
        $this->addColumn('worksheet', 'outlet_phone', 'string', '128', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('worksheet', 'cordiant_sport_175_70r13_a');
        $this->removeColumn('worksheet', 'cordiant_sport_175_70r13_b');
        $this->removeColumn('worksheet', 'cordiant_sport_175_65r14_a');
        $this->removeColumn('worksheet', 'cordiant_sport_175_65r14_b');
        $this->removeColumn('worksheet', 'cordiant_sport_175_70r14_a');
        $this->removeColumn('worksheet', 'cordiant_sport_175_70r14_b');
        $this->removeColumn('worksheet', 'cordiant_sport_185_60r14_a');
        $this->removeColumn('worksheet', 'cordiant_sport_185_60r14_b');
        $this->removeColumn('worksheet', 'cordiant_sport_185_65r14_a');
        $this->removeColumn('worksheet', 'cordiant_sport_185_65r14_b');
        $this->removeColumn('worksheet', 'cordiant_sport_185_70r14_a');
        $this->removeColumn('worksheet', 'cordiant_sport_185_70r14_b');
        $this->removeColumn('worksheet', 'cordiant_sport_185_65r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_185_65r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_195_60r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_195_60r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_195_65r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_195_65r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_205_60r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_205_60r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_205_65r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_205_65r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_205_55r16_a');
        $this->removeColumn('worksheet', 'cordiant_sport_205_55r16_b');
        $this->removeColumn('worksheet', 'cordiant_sport_215_55r16_a');
        $this->removeColumn('worksheet', 'cordiant_sport_215_55r16_b');
        $this->removeColumn('worksheet', 'cordiant_standart_175_70r13_a');
        $this->removeColumn('worksheet', 'cordiant_standart_175_70r13_b');
        $this->removeColumn('worksheet', 'cordiant_standart_175_65r14_a');
        $this->removeColumn('worksheet', 'cordiant_standart_175_65r14_b');
        $this->removeColumn('worksheet', 'cordiant_standart_175_70r14_a');
        $this->removeColumn('worksheet', 'cordiant_standart_175_70r14_b');
        $this->removeColumn('worksheet', 'cordiant_standart_185_65r14_a');
        $this->removeColumn('worksheet', 'cordiant_standart_185_65r14_b');
        $this->removeColumn('worksheet', 'cordiant_standart_185_70r14_a');
        $this->removeColumn('worksheet', 'cordiant_standart_185_70r14_b');
        $this->removeColumn('worksheet', 'cordiant_standart_185_65r15_a');
        $this->removeColumn('worksheet', 'cordiant_standart_185_65r15_b');
        $this->removeColumn('worksheet', 'cordiant_standart_195_65r15_a');
        $this->removeColumn('worksheet', 'cordiant_standart_195_65r15_b');
        $this->removeColumn('worksheet', 'cordiant_all_terrain_225_70r16_a');
        $this->removeColumn('worksheet', 'cordiant_all_terrain_225_70r16_b');
        $this->removeColumn('worksheet', 'cordiant_all_terrain_215_65r16_a');
        $this->removeColumn('worksheet', 'cordiant_all_terrain_215_65r16_b');
        $this->removeColumn('worksheet', 'cordiant_all_terrain_215_70r16_a');
        $this->removeColumn('worksheet', 'cordiant_all_terrain_215_70r16_b');
        $this->removeColumn('worksheet', 'cordiant_all_terrain_205_70r15_a');
        $this->removeColumn('worksheet', 'cordiant_all_terrain_205_70r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_175_70r13_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_175_70r13_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_175_65r14_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_175_65r14_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_185_60r14_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_185_60r14_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_185_65r14_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_185_65r14_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_185_60r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_185_60r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_195_55r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_195_55r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_195_60r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_195_60r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_195_65r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_195_65r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_205_65r15_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_205_65r15_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_205_55r16_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_205_55r16_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_205_60r16_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_205_60r16_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_215_55r16_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_215_55r16_b');
        $this->removeColumn('worksheet', 'cordiant_sport_2_215_60r16_a');
        $this->removeColumn('worksheet', 'cordiant_sport_2_215_60r16_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_155_70r13_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_155_70r13_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_185_70r14_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_185_70r14_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_205_60r16_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_205_60r16_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_185_65r14_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_185_65r14_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_195_65r15_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_195_65r15_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_205_65r15_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_205_65r15_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_205_55r16_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_205_55r16_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_185_60r14_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_185_60r14_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_175_70r13_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_175_70r13_b');
        $this->removeColumn('worksheet', 'cordiant_road_runner_175_65r14_a');
        $this->removeColumn('worksheet', 'cordiant_road_runner_175_65r14_b');
        $this->removeColumn('worksheet', 'cordiant_4_x_4_235_70r16_a');
        $this->removeColumn('worksheet', 'cordiant_4_x_4_235_70r16_b');
        $this->removeColumn('worksheet', 'cordiant_off_road_205_70r15_a');
        $this->removeColumn('worksheet', 'cordiant_off_road_205_70r15_b');
        $this->removeColumn('worksheet', 'cordiant_off_road_235_75r15_a');
        $this->removeColumn('worksheet', 'cordiant_off_road_235_75r15_b');
        $this->removeColumn('worksheet', 'cordiant_off_road_215_65r16_a');
        $this->removeColumn('worksheet', 'cordiant_off_road_215_65r16_b');
        $this->removeColumn('worksheet', 'cordiant_off_road_225_75r16_a');
        $this->removeColumn('worksheet', 'cordiant_off_road_225_75r16_b');
        $this->removeColumn('worksheet', 'cordiant_off_road_245_70r16_a');
        $this->removeColumn('worksheet', 'cordiant_off_road_245_70r16_b');
        $this->removeColumn('worksheet', 'tunga_ps_3_175/70r13_a');
        $this->removeColumn('worksheet', 'tunga_ps_3_175/70r13_b');
        $this->removeColumn('worksheet', 'tunga_camina_175_70r13_a');
        $this->removeColumn('worksheet', 'tunga_camina_175_70r13_b');
        $this->removeColumn('worksheet', 'tunga_camina_175_65r14_a');
        $this->removeColumn('worksheet', 'tunga_camina_175_65r14_b');
        $this->removeColumn('worksheet', 'tunga_camina_185_60r14_a');
        $this->removeColumn('worksheet', 'tunga_camina_185_60r14_b');
        $this->removeColumn('worksheet', 'tunga_camina_185_65r14_a');
        $this->removeColumn('worksheet', 'tunga_camina_185_65r14_b');
        $this->removeColumn('worksheet', 'tunga_camina_185_70r14_a');
        $this->removeColumn('worksheet', 'tunga_camina_185_70r14_b');
        $this->removeColumn('worksheet', 'tunga_camina_195_65r15_a');
        $this->removeColumn('worksheet', 'tunga_camina_195_65r15_b');
        $this->removeColumn('worksheet', 'comment');
        $this->removeColumn('worksheet', 'outlet_manager');
        $this->removeColumn('worksheet', 'outlet_manager_position');
        $this->removeColumn('worksheet', 'outlet_phone');
    }
}