<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addWorksheetAuditStatus extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('worksheet', 'audit_status', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('worksheet', 'audit_status');
    }
}