<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addOtletAddressIndex extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('outlet', 'address', array(
             'fields' => 
             array(
              0 => 'address',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('outlet', 'address', array(
             'fields' => 
             array(
              0 => 'address',
             ),
             ));
    }
}