<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addapplicationerror extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('application_error', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'message' => 
             array(
              'type' => 'string',
              'length' => 1000,
             ),
             'type' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'file' => 
             array(
              'type' => 'string',
              'length' => 500,
             ),
             'line' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'trace' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'code' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'module' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'action' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'uri' => 
             array(
              'type' => 'string',
              'length' => 500,
             ),
             'user' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'comment' => 
             array(
              'type' => 'clob',
              'length' => NULL,
             ),
             'severity' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'low',
              1 => 'medium',
              2 => 'high',
              3 => 'critical',
              ),
              'default' => 'medium',
              'length' => NULL,
             ),
             'user_agent' => 
             array(
              'type' => 'string',
              'length' => 100,
             ),
             'created_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             'updated_at' => 
             array(
              'notnull' => true,
              'type' => 'timestamp',
              'length' => 25,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('application_error');
    }
}