<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addDistributor extends Doctrine_Migration_Base
{
	public function up()
	{
		$this->createTable('distributor', array(
			'id'   =>
			array(
				'type'          => 'integer',
				'unsigned'      => '1',
				'primary'       => '1',
				'autoincrement' => '1',
				'length'        => '11',
			),
			'name' =>
			array(
				'type'    => 'string',
				'notnull' => '1',
				'length'  => '255',
			),
		), array(
			'indexes' =>
			array(
				'name_idx' =>
				array(
					'fields' =>
					array(
						0 => 'name',
					),
				),
			),
			'primary' =>
			array(
				0 => 'id',
			),
			'collate' => 'utf8_general_ci',
			'charset' => 'utf8',
		));
		$this->removeColumn('outlet', 'distributor');
		$this->addColumn('outlet', 'distributor_id', 'integer', '11', array(
			'notnull'  => '1',
			'unsigned' => '1',
		));
	}

	public function down()
	{
		$this->dropTable('distributor');
		$this->addColumn('outlet', 'distributor', 'string', '255', array(
			'notnull' => '1',
		));
		$this->removeColumn('outlet', 'distributor_id');
	}
}