<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class changeHistoryCommentToText extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('history', 'comment', 'text');
    }

    public function down()
    {

    }
}