<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addWorksheetAuditor extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('worksheet', 'worksheet_auditor_id_sf_guard_user_id', array(
             'name' => 'worksheet_auditor_id_sf_guard_user_id',
             'local' => 'auditor_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             ));
        $this->addIndex('worksheet', 'worksheet_auditor_id', array(
             'fields' => 
             array(
              0 => 'auditor_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('worksheet', 'worksheet_auditor_id_sf_guard_user_id');
        $this->removeIndex('worksheet', 'worksheet_auditor_id', array(
             'fields' => 
             array(
              0 => 'auditor_id',
             ),
             ));
    }
}