<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addPhotoAndAudioWorksheetStatus extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('worksheet', 'photo_status', 'integer', '4', array(
             ));
        $this->addColumn('worksheet', 'audio_status', 'integer', '4', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('worksheet', 'photo_status');
        $this->removeColumn('worksheet', 'audio_status');
    }
}