<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addSfGuardRegionSchema extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('sf_guard_user_region_schema', array(
             'user_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             'region_id' => 
             array(
              'type' => 'integer',
              'primary' => '1',
              'length' => '8',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'user_id',
              1 => 'region_id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('sf_guard_user_region_schema');
    }
}