<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addWorksheetStatusIndexes extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('worksheet', 'status_idx', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->addIndex('worksheet', 'photo_status_idx', array(
             'fields' => 
             array(
              0 => 'photo_status',
             ),
             ));
        $this->addIndex('worksheet', 'audio_status_idx', array(
             'fields' => 
             array(
              0 => 'audio_status',
             ),
             ));
    }

    public function down()
    {
        $this->removeIndex('worksheet', 'status_idx', array(
             'fields' => 
             array(
              0 => 'status',
             ),
             ));
        $this->removeIndex('worksheet', 'photo_status_idx', array(
             'fields' => 
             array(
              0 => 'photo_status',
             ),
             ));
        $this->removeIndex('worksheet', 'audio_status_idx', array(
             'fields' => 
             array(
              0 => 'audio_status',
             ),
             ));
    }
}