<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addoutlet extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('outlet', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => true,
              'primary' => true,
              'autoincrement' => true,
              'length' => 11,
             ),
             'distributor' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'lagal_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'actual_name' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'region_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'unsigned' => true,
              'length' => 11,
             ),
             'city_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'unsigned' => true,
              'length' => 11,
             ),
             'address' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 255,
             ),
             'type' => 
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'specialized',
              1 => 'auto',
              2 => 'market',
              ),
              'notnull' => true,
              'length' => NULL,
             ),
             'group_type' =>
             array(
              'type' => 'enum',
              'values' => 
              array(
              0 => 'a',
              1 => 'b',
              ),
              'notnull' => true,
              'length' => NULL,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('outlet');
    }
}