<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class addHistoryModel extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('history', array(
             'id' => 
             array(
              'type' => 'integer',
              'unsigned' => '1',
              'primary' => '1',
              'autoincrement' => '1',
              'length' => '8',
             ),
             'event' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'unsigned' => '1',
              'length' => '4',
             ),
             'model' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'model_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'user_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             'comment' => 
             array(
              'type' => 'string',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'indexes' => 
             array(
              'event' => 
              array(
              'fields' => 
              array(
               0 => 'event',
              ),
              ),
              'model' => 
              array(
              'fields' => 
              array(
               0 => 'model',
              ),
              ),
              'model_id' => 
              array(
              'fields' => 
              array(
               0 => 'model_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
    }

    public function down()
    {
        $this->dropTable('history');
    }
}