<?php

/**
 * PluginsfGuardUserCitySchemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserCitySchemaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardUserCitySchemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardUserCitySchema');
    }
}