<?php

/**
 * PluginsfGuardUserRegionSchemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserRegionSchemaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardUserRegionSchemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardUserRegionSchema');
    }
}