<?php

/**
 * PluginsfGuardUserSchemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginsfGuardUserSchemaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginsfGuardUserSchemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginsfGuardUserSchema');
    }
}