Country:
  columns:
    id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
      primary:        true
      autoincrement:  true
    name:
      type:           string(255)
      notnull:        true

Region:
  columns:
    id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
      primary:        true
      autoincrement:  true
    country_id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
    name:
      type:           string(255)
      notnull:        true
  relations:
    Country:
      local:          country_id
      foreign:        id
      foreignAlias:   Rigions
  indexes:
    name:
      fields:         [name]

City:
  columns:
    id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
      primary:        true
      autoincrement:  true
    country_id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
    region_id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
    name:
      type:           string(255)
      notnull:        true
  relations:
    Country:
      local:          country_id
      foreign:        id
      foreignAlias:   Cities
    Region:
      local:          region_id
      foreign:        id
      foreignAlias:   Rigions
  indexes:
    name:
      fields:         [name]

Outlet:
  columns:
    id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
      primary:        true
      autoincrement:  true
    distributor_id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
    lagal_name:
      type:           string(255)
      notnull:        true
    actual_name:
      type:           string(255)
      notnull:        true
    region_id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
    city_id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
    address:
      type:           string(255)
      notnull:        true
    type:
      type:           enum
      values:
        - specialized
        - auto
        - market
      notnull:        true
    group_type:
      type:           enum
      values:
        - a
        - b
      notnull:        true
  relations:
    Region:
      local:          region_id
      foreign:        id
      foreignAlias:   Outlets
    City:
      local:          city_id
      foreign:        id
      foreignAlias:   Outlets
    Distributor:
      local:          distributor_id
      foreign:        id
      foreignAlias:   Outlets
  indexes:
    type:
      fields:         [type]
    group_type:
      fields:         [group_type]
    legal_name:
      fields:         [legal_name]
    actual_name:
      fields:         [actual_name]

Distributor:
  columns:
    id:
      type:           integer(11)
      notnull:        true
      unsigned:       true
      primary:        true
      autoincrement:  true
    name:
      type:           string(255)
      notnull:        true
  indexes:
    name:
      fields:         [name]
